version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  location-service:
    build: .
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SSL=false
      - KAFKA_BROKERS=localhost:9092
    depends_on:
      - redis
